name: Deploy Docker Compose

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  push:
    branches:
      - main

jobs:
  finish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "Deploy"

            
