name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

#    services: # 컨테이너, docker-compose 설정과 거의 유사
#      db:
#        image: mysql:8.0
#        env:
#          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }} # github에 등록한 환경변수
#        ports:
#          - 3306:3306

    steps:
      - name: ls all
        run: ls -al
#    - name: Checkout
#      uses: actions/checkout@v3
#
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#
#    - name: Build with Gradle
#      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#      with:
#        arguments: build
#    - name: Upload artifact
#      uses: actions/upload-artifact@v2
#      with:
#          name: cicdsample
#          path: build/libs/*.jar
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#    - name: Download artifact
#      uses: actions/download-artifact@v3
#      with:
#        name: cicdsample
#        path: build/libs
#
#    - name: Deploy
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.SERVER_IP }}
#        username: ubuntu
#        key: ${{ secrets.SSH_PRIVATE_KEY }}
#        script: |
#          cd CICD
#          ls
